### ISSUE TITLE
"update" is unchecked in the launcher at first start

### ISSUE THREAD

**Issue by abma** [flathub/info.beyondallreason.bar#32] opened 2022-09-30 21:24 UTC
this is confusing, as this just leads to an error message when starting.

not sure if this a bug in the flatpak or should be reported upstream.

**Comment by p2004a** [comment] 2022-09-30 21:48
Hi @abma, thank you for reporting, the "update" unchecked was an unfortunate regression that was already fixed upstream https://github.com/gajop/spring-launcher/pull/118 and update will be pushed in few days.

For the second issue, of "alpha" configuration not working, could you please share log from the launcher that shows errors reported by pr-downloader please? This is first report of issues with this new download method reported we've got so I would really like to get more information about it.

**Comment by p2004a** [comment] 2022-09-30 22:41
Thank you for this additional information!

Index files are on CDN and are updated after all the pool chunks are uploaded, so that is unlikely (It's not just plain CDN on top of repos.springrts.com but a full mirror). It doesn't looks like issue from CDN because the log you shared doesn't have any HTTP errors that would be automatically retried anyway, it looks like error happened more on the local side.

It looks like what failed was in a code path that doesn't unfortunately actually have error printed out before failing :/, I've thought all had that, but now that I audit stuff I see that at least e.g. `CFileSystem::Rename` doesn't. I've opened https://github.com/beyond-all-reason/pr-downloader/issues/26 to track that improvement to logging.

I will keep this issue open until the "update" button fix rolls out.

**Comment by p2004a** [comment] 2022-10-09 18:04
Closing, as new version with fix was rolled out today.

**Closed by p2004a** 2022-10-09 18:04 UTC
